[[pages]]
path = "pages/start_front.py"
name = "í™ˆ"
icon = "ğŸ "

[[pages]]
path = "pages/tester.py"
name = "API í…ŒìŠ¤íŠ¸"
icon = "ğŸ§ª"

[[pages]]
path = "pages/prompt_history.py"
name = "í”„ë¡¬í”„íŠ¸ ì´ë ¥"
icon = "ğŸ“"

[[pages]]
path = "pages/view_data_history.py"
name = "ì‹¤í—˜ì‹¤"
icon = "ğŸ”¬"

[[pages]]
path = "pages/setting.py"
name = "í™˜ê²½ì„¤ì •"
icon = "âš™ï¸"
